plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // 若存在 NeoForge AccessTransformer 文件则自动启用
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // 统一运行配置名称,与 fabric 保持一致
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        data {
            clientData()
            gameDirectory = this.mkdir(this.file('runs/data'))
            // 数据生成可通过 "./gradlew :neoforge:runData" 运行
            // 指定数据生成的 modid、输出目录及现有资源目录
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            this.file('runs/server').createParentDirectories()
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }